<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd" version="3.0" name="com.leonardo.dao.VendaDAOTest" time="1.083" tests="11" errors="11" skipped="0" failures="0">
  <properties>
    <property name="java.specification.version" value="21"/>
    <property name="sun.cpu.isalist" value="amd64"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.class.path" value="D:\repositorios\Backend-Java\EBAC\mod35 - Trocar no reposi4tório a lógica de salvar em JDBC para JPA\projeto4-final\modulo35\target\test-classes;D:\repositorios\Backend-Java\EBAC\mod35 - Trocar no reposi4tório a lógica de salvar em JDBC para JPA\projeto4-final\modulo35\target\classes;C:\Users\masco\.m2\repository\org\projectlombok\lombok\1.18.38\lombok-1.18.38.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-suite\1.10.2\junit-platform-suite-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-suite-api\1.10.2\junit-platform-suite-api-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-commons\1.10.2\junit-platform-commons-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-suite-engine\1.10.2\junit-platform-suite-engine-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-suite-commons\1.10.2\junit-platform-suite-commons-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-launcher\1.10.2\junit-platform-launcher-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.10.0\junit-jupiter-engine-5.10.0.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-engine\1.10.0\junit-platform-engine-1.10.0.jar;C:\Users\masco\.m2\repository\org\opentest4j\opentest4j\1.3.0\opentest4j-1.3.0.jar;C:\Users\masco\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.10.0\junit-jupiter-api-5.10.0.jar;C:\Users\masco\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;C:\Users\masco\.m2\repository\com\github\javafaker\javafaker\1.0.2\javafaker-1.0.2.jar;C:\Users\masco\.m2\repository\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\masco\.m2\repository\org\yaml\snakeyaml\1.23\snakeyaml-1.23-android.jar;C:\Users\masco\.m2\repository\com\github\mifmif\generex\1.0.2\generex-1.0.2.jar;C:\Users\masco\.m2\repository\dk\brics\automaton\automaton\1.11-8\automaton-1.11-8.jar;C:\Users\masco\.m2\repository\org\postgresql\postgresql\42.7.6\postgresql-42.7.6.jar;C:\Users\masco\.m2\repository\org\checkerframework\checker-qual\3.49.3\checker-qual-3.49.3.jar;C:\Users\masco\.m2\repository\javax\persistence\javax.persistence-api\2.2\javax.persistence-api-2.2.jar;"/>
    <property name="java.vm.vendor" value="Eclipse Adoptium"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="user.variant" value=""/>
    <property name="java.vendor.url" value="https://adoptium.net/"/>
    <property name="user.timezone" value="America/Sao_Paulo"/>
    <property name="os.name" value="Windows 11"/>
    <property name="java.vm.specification.version" value="21"/>
    <property name="user.country" value="BR"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.boot.library.path" value="C:\Users\masco\AppData\Local\Programs\Eclipse Adoptium\jdk-21.0.6.7-hotspot\bin"/>
    <property name="sun.java.command" value="C:\Users\masco\AppData\Local\Temp\surefire393123322882608569\surefirebooter-20250623162345101_3.jar C:\Users\masco\AppData\Local\Temp\surefire393123322882608569 2025-06-23T16-23-44_954-jvmRun1 surefire-20250623162345101_1tmp surefire_0-20250623162345101_2tmp"/>
    <property name="jdk.debug" value="release"/>
    <property name="test" value="com.leonardo.dao.VendaDAOTest"/>
    <property name="surefire.test.class.path" value="D:\repositorios\Backend-Java\EBAC\mod35 - Trocar no reposi4tório a lógica de salvar em JDBC para JPA\projeto4-final\modulo35\target\test-classes;D:\repositorios\Backend-Java\EBAC\mod35 - Trocar no reposi4tório a lógica de salvar em JDBC para JPA\projeto4-final\modulo35\target\classes;C:\Users\masco\.m2\repository\org\projectlombok\lombok\1.18.38\lombok-1.18.38.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-suite\1.10.2\junit-platform-suite-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-suite-api\1.10.2\junit-platform-suite-api-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-commons\1.10.2\junit-platform-commons-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-suite-engine\1.10.2\junit-platform-suite-engine-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-suite-commons\1.10.2\junit-platform-suite-commons-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-launcher\1.10.2\junit-platform-launcher-1.10.2.jar;C:\Users\masco\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.10.0\junit-jupiter-engine-5.10.0.jar;C:\Users\masco\.m2\repository\org\junit\platform\junit-platform-engine\1.10.0\junit-platform-engine-1.10.0.jar;C:\Users\masco\.m2\repository\org\opentest4j\opentest4j\1.3.0\opentest4j-1.3.0.jar;C:\Users\masco\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.10.0\junit-jupiter-api-5.10.0.jar;C:\Users\masco\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;C:\Users\masco\.m2\repository\com\github\javafaker\javafaker\1.0.2\javafaker-1.0.2.jar;C:\Users\masco\.m2\repository\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\masco\.m2\repository\org\yaml\snakeyaml\1.23\snakeyaml-1.23-android.jar;C:\Users\masco\.m2\repository\com\github\mifmif\generex\1.0.2\generex-1.0.2.jar;C:\Users\masco\.m2\repository\dk\brics\automaton\automaton\1.11-8\automaton-1.11-8.jar;C:\Users\masco\.m2\repository\org\postgresql\postgresql\42.7.6\postgresql-42.7.6.jar;C:\Users\masco\.m2\repository\org\checkerframework\checker-qual\3.49.3\checker-qual-3.49.3.jar;C:\Users\masco\.m2\repository\javax\persistence\javax.persistence-api\2.2\javax.persistence-api-2.2.jar;"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="user.home" value="C:\Users\masco"/>
    <property name="user.language" value="pt"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.version.date" value="2025-01-21"/>
    <property name="java.home" value="C:\Users\masco\AppData\Local\Programs\Eclipse Adoptium\jdk-21.0.6.7-hotspot"/>
    <property name="file.separator" value="\"/>
    <property name="basedir" value="D:\repositorios\Backend-Java\EBAC\mod35 - Trocar no reposi4tório a lógica de salvar em JDBC para JPA\projeto4-final\modulo35"/>
    <property name="java.vm.compressedOopsMode" value="Zero based"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="surefire.real.class.path" value="C:\Users\masco\AppData\Local\Temp\surefire393123322882608569\surefirebooter-20250623162345101_3.jar"/>
    <property name="user.script" value=""/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="java.runtime.version" value="21.0.6+7-LTS"/>
    <property name="user.name" value="masco"/>
    <property name="stdout.encoding" value="Cp1252"/>
    <property name="path.separator" value=";"/>
    <property name="os.version" value="10.0"/>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="java.vendor.version" value="Temurin-21.0.6+7"/>
    <property name="maven.ext.class.path" value="C:\Users\masco\.vscode\extensions\oracle.oracle-java-24.0.0\nbcode\java\maven-nblib\netbeans-eventspy.jar"/>
    <property name="localRepository" value="C:\Users\masco\.m2\repository"/>
    <property name="java.vendor.url.bug" value="https://github.com/adoptium/adoptium-support/issues"/>
    <property name="java.io.tmpdir" value="C:\Users\masco\AppData\Local\Temp\"/>
    <property name="java.version" value="21.0.6"/>
    <property name="user.dir" value="D:\repositorios\Backend-Java\EBAC\mod35 - Trocar no reposi4tório a lógica de salvar em JDBC para JPA\projeto4-final\modulo35"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="native.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\Users\masco\AppData\Local\Programs\Eclipse Adoptium\jdk-21.0.6.7-hotspot\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\masco\AppData\Local\Programs\Eclipse Adoptium\jdk-21.0.6.7-hotspot\bin;C:\Users\masco\AppData\Local\Microsoft\WindowsApps;C:\Users\masco\AppData\Local\Programs\Microsoft VS Code\bin;."/>
    <property name="java.vm.info" value="mixed mode, sharing"/>
    <property name="stderr.encoding" value="Cp1252"/>
    <property name="java.vendor" value="Eclipse Adoptium"/>
    <property name="java.vm.version" value="21.0.6+7-LTS"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="java.class.version" value="65.0"/>
  </properties>
  <testcase name="removerApenasUmProduto" classname="com.leonardo.dao.VendaDAOTest" time="0.378">
    <error message="Cannot invoke &quot;java.lang.Integer.intValue()&quot; because the return value of &quot;com.leonardo.domain.Produto.getQuantidadeEstoque()&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.leonardo.domain.Produto.getQuantidadeEstoque()" is null
	at com.leonardo.infrastructure.dao.produto.ProdutoDAO.setParametrosQueryInsercao(ProdutoDAO.java:71)
	at com.leonardo.infrastructure.dao.produto.ProdutoDAO.setParametrosQueryInsercao(ProdutoDAO.java:22)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:98)
	at com.leonardo.dao.VendaDAOTest.cadastrarProduto(VendaDAOTest.java:293)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:57)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
]]></error>
  </testcase>
  <testcase name="salvarVendaMesmoCodigoExistente" classname="com.leonardo.dao.VendaDAOTest" time="0.048">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
  <testcase name="finalizarVenda" classname="com.leonardo.dao.VendaDAOTest" time="0.046">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
  <testcase name="cancelarVenda" classname="com.leonardo.dao.VendaDAOTest" time="0.043">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
  <testcase name="salvar" classname="com.leonardo.dao.VendaDAOTest" time="0.043">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
  <testcase name="tentarAdicionarProdutosVendaFinalizada" classname="com.leonardo.dao.VendaDAOTest" time="0.046">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
  <testcase name="removerTodosProdutos" classname="com.leonardo.dao.VendaDAOTest" time="0.047">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
  <testcase name="adicionarMaisProdutosDiferentes" classname="com.leonardo.dao.VendaDAOTest" time="0.046">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
  <testcase name="adicionarMaisProdutosDoMesmo" classname="com.leonardo.dao.VendaDAOTest" time="0.041">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
  <testcase name="removerProduto" classname="com.leonardo.dao.VendaDAOTest" time="0.149">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
  <testcase name="pesquisar" classname="com.leonardo.dao.VendaDAOTest" time="0.15">
    <error message="ERRO CADASTRANDO OBJETO " type="com.leonardo.exceptions.DAOException"><![CDATA[com.leonardo.exceptions.DAOException: ERRO CADASTRANDO OBJETO 
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:112)
	at com.leonardo.dao.VendaDAOTest.cadastrarCliente(VendaDAOTest.java:306)
	at com.leonardo.dao.VendaDAOTest.init(VendaDAOTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: com.leonardo.exceptions.DAOException: ERRO EXLUINDO OBJETO 
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:338)
		at com.leonardo.dao.VendaDAOTest.excluirVendas(VendaDAOTest.java:322)
		at com.leonardo.dao.VendaDAOTest.end(VendaDAOTest.java:62)
		... 3 more
	Caused by: org.postgresql.util.PSQLException: ERRO: relação "tb_produto_quantidade" não existe
  Posição: 13
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
		at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
		at com.leonardo.dao.VendaDAOTest.executeDelete(VendaDAOTest.java:335)
		... 5 more
Caused by: org.postgresql.util.PSQLException: ERRO: duplicar valor da chave viola a restrição de unicidade "uk_cpf_cliente"
  Detalhe: Chave (cpf)=(12312312312) já existe.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2423)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:374)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:157)
	at com.leonardo.infrastructure.dao.generic.GenericDAO.cadastrar(GenericDAO.java:99)
	... 5 more
]]></error>
  </testcase>
</testsuite>